## Assignments

Son Huynh
31.01.2020

In [1]:
import numpy as np

### Question 1

In [15]:
np.random.seed(123)

a = np.random.randint(1, 11, 20).reshape(5, 4)

a  

array([[ 3,  3,  7,  2],
       [ 4, 10,  7,  2],
       [ 1,  2, 10,  1],
       [ 1, 10,  4,  5],
       [ 1,  1,  5,  2]])

#### 1.1 There are two number 7 in array `a`. Can you use slicing to get them?

In [5]:
a[:2,2]

array([7, 7])

#### 1.2 Calculate the sum of each column, assign the result to an array called `sum_a`

In [8]:
sum_a = a.sum(axis=0)
sum_a

array([10, 26, 33, 12])

#### 1.3 Change the elements of array a into percentage of the respective column. For example, the first column should become `[0.3, 0.4, 0.1, 0.1, 0.1]`

In [16]:
a = a/sum_a
a

array([[0.3       , 0.11538462, 0.21212121, 0.16666667],
       [0.4       , 0.38461538, 0.21212121, 0.16666667],
       [0.1       , 0.07692308, 0.3030303 , 0.08333333],
       [0.1       , 0.38461538, 0.12121212, 0.41666667],
       [0.1       , 0.03846154, 0.15151515, 0.16666667]])

#### 1.4 Use the `.sort()` method to sort array `a` by column. 

There are several functions and methods for python and its libraries. You should try google and official documentations to learn different techniques that we haven't covered in our lectures. For example you can read about the available methods for numpy array here: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

In [18]:
a.sort(axis=0)
a

array([[0.1       , 0.03846154, 0.12121212, 0.08333333],
       [0.1       , 0.07692308, 0.15151515, 0.16666667],
       [0.1       , 0.11538462, 0.21212121, 0.16666667],
       [0.3       , 0.38461538, 0.21212121, 0.16666667],
       [0.4       , 0.38461538, 0.3030303 , 0.41666667]])

### Question 2

In [29]:
np.random.seed(23)

b = np.random.randint(1,11, [5,4])

b

array([[ 4,  7,  9, 10],
       [ 7,  9,  8, 10],
       [ 4,  7,  2,  3],
       [ 6,  6,  1,  6],
       [ 1, 10, 10,  4]])

#### Find the maximum number for each row, considering only the first 3 columns

The output should be `array([9, 9, 7, 6, 10])`

In [35]:
b[:,0:3].max(axis=1) # using indexes 0 to 3 or;
b[:,:-1].max(axis=1) # since we know that there are 4 columns we just remove the last index

array([ 9,  9,  7,  6, 10])

### Question 3

In [36]:
c = np.array([1,2,3,np.nan,5,6,7,np.nan])

#### In numpy, a missing value (blank value) is denoted as `np.nan`. Find out how many missing values is in array `c`.

Hint: check out `np.isnan()` and `np.count_nonzero()`

In [40]:
# isnan on array will return either True or False. Falses are interpreted as 0 so count_nonzero will be only 2. 
np.count_nonzero(np.isnan(c))

2

### Question 4 (optional)

__4.1__ Create two arrays `a, b` sampled randomly from a uniform distribution within the range `[0,1]`.

Array `a` has 100 numbers and array `b` has 80 numbers.

In [54]:
import random
a  = np.random.uniform(low=0, high=1, size=(100))
b = np.random.uniform(low=0, high=1, size=(80))

__4.2__ Find out the mean and variance of `a` and `b`

In [66]:
print(f"mean of a = {a.mean():.4f}")
print(f"var of a = {a.var():.4f}")

print(f"mean of b = {b.mean():.4f}")
print(f"var of b = {b.var():.4f}")



mean of a = 0.4990
var of a = 0.0805
mean of b = 0.4773
var of b = 0.0888


__4.3__ Perform a two-sample t-test to find out if the difference between `a` and `b`'s means are statistically significant.

For this task you can import the `stats` module from scipy and use the `ttest_ind` function. Scipy is similar to numpy, but contains scientific functions that complement numpy.

Learn about 2-sample t-test:
https://stattrek.com/statistics/dictionary.aspx?definition=two-sample%20t-test

In [67]:
from scipy import stats

stats.ttest_ind(a,b, equal_var = False)

Ttest_indResult(statistic=0.49221605211387814, pvalue=0.6232187624654745)

### Question 5 (optional)

#### Comparison between for-loop and numpy performance:

The function below simulates how many times on average the number 1 appears if you randomly select 100 numbers from 1 to 10. The simulation is run 10000 times.

In [68]:
import random

In [69]:
def simulation():
    results = []
    for _ in range(10000):
        l = []
        for _ in range(100):
            if random.randrange(1,11) == 1:
                l.append(True)
            else:
                l.append(False)
        results.append(sum(l))
    return (sum(results) / len(results))

Running simulation() should give us a result very close to 10.

In [70]:
simulation()

10.0244

Now recreate the simulation with numpy and without using for-loop and if-else.

Hint:
- You can use the table structure (row, column) to do this task
- You can translate an array into a same-size boolean array (True/False) by some condition. For example: new_array = (old_array == 1)
- In Python, True equals 1 and False equals 0

In [81]:
import numpy

def simulation_np():
    
    
    sample = np.array(10)
    
    print(sample)
    
simulation_np()

10


Now use %timeit in front of your code line to compare the run time between simulation() and numpy code. If your code has multiple lines, put it inside a funtion and use %timeit before the function call.

Try changing the number of simulations from 10000 to 100000 in both approaches to see how fast numpy can be when the task gets bigger.

In [ ]:
%timeit simulation()

In [ ]:
%timeit # your code

### More about numpy

We don't often use numpy syntax in common data analysis tasks. However, it is the core library that other more used libraries are built upon (pandas, scikit-learn, ...). If you want to learn more about the philosophy behind numpy's vectorization, here is one good resource.

https://www.labri.fr/perso/nrougier/from-python-to-numpy/